[[reg]]
path =  "asset\\register\\dat"
name = "dat"

[[reg]]
name = "dat.mesh" 
path =  "asset\\register\\dat\\mesh"

[[reg]]
name = "dat.shader"
path =  "asset\\register\\dat\\shader"

[[reg]]
name = "dat.model"
path =  "asset\\register\\dat\\model"

[[reg]]
name = "dat.zone"
path =  "asset\\register\\dat\\zone"

[[reg]]
name = "exe"
path =  "asset\\register\\exe"
